# Generated by Django 5.0.4 on 2024-09-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_room_roomimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='standings',
        ),
    ]
