# Generated by Django 5.0.4 on 2024-09-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_room_standings'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
