# Generated by Django 5.0.4 on 2024-09-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_room_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roomimage',
            options={},
        ),
    ]
