# Generated by Django 5.0.4 on 2024-09-23 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_room_options_alter_roomimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='roomimage',
            options={'verbose_name_plural': 'Room Images'},
        ),
    ]
