# Generated by Django 5.0.4 on 2024-09-24 09:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_room_options_alter_roomimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('location', models.IntegerField(blank=True, default=5, null=True)),
                ('staff', models.IntegerField(blank=True, default=5, null=True)),
                ('cleanliness', models.IntegerField(blank=True, default=5, null=True)),
                ('value_for_money', models.IntegerField(blank=True, default=5, null=True)),
                ('comfort', models.IntegerField(blank=True, default=5, null=True)),
                ('facilities', models.IntegerField(blank=True, default=5, null=True)),
                ('free_wifi', models.IntegerField(blank=True, default=5, null=True)),
                ('status', models.BooleanField(blank=True, default=5, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.room')),
            ],
            options={
                'verbose_name_plural': 'Room Reviews',
            },
        ),
    ]
