# Generated by Django 5.0.4 on 2024-09-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_roomreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreview',
            name='status',
            field=models.BooleanField(blank=True, default=1, null=True),
        ),
    ]
