# Generated by Django 5.0.4 on 2024-09-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_testimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
