# Generated by Django 5.0.4 on 2024-09-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
