# Generated by Django 5.0.4 on 2024-09-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_setting_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='second_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
