# Generated by Django 5.0.4 on 2024-10-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_room_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='price',
            new_name='price_rwf',
        ),
        migrations.AddField(
            model_name='room',
            name='price_usd',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
