# Generated by Django 5.0.4 on 2024-10-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_booking_currency_booking_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='about_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='about_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
