# Generated by Django 5.0.4 on 2024-10-10 19:04

import home.models
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_setting_about_description_setting_about_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='about_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=home.models.about_image_path),
        ),
    ]
