# Generated by Django 5.0.4 on 2024-10-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_setting_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='about_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
