# Generated by Django 5.0.4 on 2024-10-17 08:46

import django.utils.timezone
import home.models
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('price_usd', models.IntegerField(blank=True, null=True)),
                ('price_rwf', models.IntegerField(blank=True, null=True)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=home.models.food_image_path)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Food',
            },
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=home.models.room_image_path),
        ),
    ]
