# Generated by Django 5.0.4 on 2025-06-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_setting_hero_desc_setting_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='service_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='service_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
