# Generated by Django 5.0.4 on 2025-06-25 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_setting_service_desc_setting_service_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='service_desc',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='service_title',
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=255)),
                ('service_desc', models.TextField()),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='home.setting')),
            ],
        ),
    ]
