# Generated by Django 5.0.4 on 2025-06-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_setting_service_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('drinks', 'Drinks'), ('food', 'Food')], default='food', max_length=10),
        ),
    ]
